# name: "Frontend Tests"

# on: [push]

#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     pull_request:

# defaults:
#   run:
#     working-directory: ./Top5Lister/client


# permissions:
#   contents: read
#   pull-requests: read

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           # cd: cd ./Top5Lister/client
#           build: npm run build
#           start: npm start
name: Frontend Test Workflow
on: push # Run this workflow whenever a push occurs
jobs:
  e2e-test:
    runs-on: ubuntu-latest # Run the job on an Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the latest code from the repository
      - name: Install dependencies
        run: cd Top5Lister/client && npm install # Change to the client directory and install dependencies
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2 # Use the official Cypress GitHub Action
        with:
          working-directory: Top5Lister/client
          browser: chrome # Use Chrome browser for testing
          record: true # Record test results on the Cypress Dashboard
          spec: Top5Lister/client/cypress/e2e/spec.cy.js # Specify the path to your test script