# name: "Frontend Tests"

# on: [push]

#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     pull_request:

# defaults:
#   run:
#     working-directory: ./Top5Lister/client


# permissions:
#   contents: read
#   pull-requests: read

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Cypress run
#         uses: cypress-io/github-action@v5
#         with:
#           # cd: cd ./Top5Lister/client
#           build: npm run build
#           start: npm start
name: Frontend Test Workflow
on: push # Run this workflow whenever a push occurs
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2.4.2
      #   with:
      #     node-version: '14.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./Top5Lister/client

      - name: Start server
        run: npm start
        working-directory: ./Top5Lister/server

      - name: Wait for server to start
        run: |
          npx wait-on http://localhost:3000
        working-directory: ./Top5Lister/client

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'